### ISSUE TITLE
[8.0] [Question] mrp_production_add_middle_stuff - when would you use this module?

### ISSUE THREAD

**Issue by bistaray** [odoomrp/odoomrp-wip#1099]
Hello.

In v8 (without this module) I can add raw materials to a MANUFACTURING ORDER (MO) on the popup when I click PRODUCE (it lists what I am supposed to consume, but I can change quantities and even add a brand new raw material on this list).  Whatever is changed on this popup is reflected in the CONSUMED PRODUCTS list on the MO, and additional stock moves are created from STOCK to PRODUCTION, correctly decreasing Inventory.

My question is, when would I need to use the mrp_production_add_middle_stuff module?  Looking at the code, it seems the module marks any additional products so the user can tell what was added - is that the reason?

**Comment by anajuaristi** [comment]
No. The reason is that you may want to plan extra materials to be consumed after the mo is launched.
With this module you can check availability or any other action you need to do with materials on the mo. You don't need to wait until production wizard is launchex but you can prepare extra materials to be consumed when you know you will need them.

**Comment by anajuaristi** [comment]
No. The reason is that you may want to plan extra materials to be consumed after the mo is launched.
With this module you can check availability or any other action you need to do with materials on the mo. You don't need to wait until production wizard is launched but you can prepare extra materials to be consumed when you know you will need them.

**Comment by bistaray** [comment]
Thanks!!  So it is more flexible.  (1) Without the module you can add materials at the initial CONSUME stage, or at the final PRODUCE stage, but with this module you can do it anytime.  (2) It allows you to add the material without using it, so you can check availability first, and manage the addition in multiple steps -> add, scrap, add, consume.  Without this module you have to add and consume in one step.

**Comment by anajuaristi** [comment]
Exactly. That's it :)

**Comment by anajuaristi** [comment]
Closing issue as it seems it have been answered 
@bistaray if you have got any other concern, please open another issue.
