### ISSUE TITLE
[8.0][sale_product_variant_type] procurement does not accept range custom value

### ISSUE THREAD

**Issue by roedeorm** [odoomrp/odoomrp-wip#1163]
Place a sales order with a manufacture/mto product which has attribute type range and enter a custom value. Example: Attribute 'length', min=10.0, max=50.0
Running the procurement yields below error eventhough the custom value has been entered within the range in the sale order line.

ValidateError
Error while validating constraint
Custom value for attribute 'length' must be between 10.0 and 50.0. 

Tested on 
http://demo.odoomrp.com
db=September_2015_EN

**Comment by anajuaristi** [comment]
Yes, this is a known error since longtime. We did not have time to solve it.
The problem is the custom value set on sales order line configurator is not filling the custom field on MO configurator. As this field is mandatory the MO can not be saved and you obtain the error.

We are quite busy but we will try to solve asap.  
@oihane or @mikelarre please take care of it.

@roedeorm Thank you for make us remember it:

Ana
