### ISSUE TITLE
Work Center dropdown field Not Populating

### ISSUE THREAD

**Issue by LDNail** [odoomrp/odoomrp-wip#1212]
Bare Odoo 8 on patched Ubuntu 14.04.  
Install MRP_Operations_Extension module
Logs confirm successful install.

Go to Manufacturing > Configuration > Work Centers > Create several Work Centers

Go to Manufacturing > Work Orders > Create a new Work Order

Select the Work Center field drop down and the Work Centers do not populate
<img width="859" alt="screen shot 2016-05-03 at 10 50 49 pm" src="https://cloud.githubusercontent.com/assets/18720271/15004830/8bac166e-1181-11e6-888b-273d1afa990a.png">

If you create a new Work Center through _Create and Edit..._ function, confirm that it does create a new Work Center in the Work Centers list, but again it does not show when use the drop down.
<img width="350" alt="screen shot 2016-04-26 at 11 29 38 pm" src="https://cloud.githubusercontent.com/assets/18720271/15004899/8c07d26e-1182-11e6-9033-7fc4534b75ee.png">

If I uninstall module, and create a Work Order, it looks like:
<img width="850" alt="screen shot 2016-05-03 at 10 47 17 pm" src="https://cloud.githubusercontent.com/assets/18720271/15004854/cc57b3bc-1181-11e6-85fe-38594760bfe4.png">

**Comment by pedrobaeza** [comment]
I think this is because you need to enable routes and create a route that contains that work center.

**Comment by LDNail** [comment]
I enabled **Manage routings and work orders** & created some a few simple routing rules.. still no joy.

**Comment by pedrobaeza** [comment]
It can be a misconfiguration, but again, it's working on our side.

**Comment by anajuaristi** [comment]
@LDNail 
I think there is a misconfiguration

First one: You should not create manual workorders since they are automatically created from BOM configuration.
You should go on with this steps:
1. Create a bom
2. Create a routing
3. Assing routing to bom, and... very important --> Assign the routing step to be consumed on each material bom line.
4. Create an MO for this product/bom
5. Calculate data --> It should create automatically all Workorders with correct work centers

---

To create manually workorders in a manufacturing order, try first to assing "Manufacturing order" field.
It could be that workcenters are limited to the ones selected on MO routing. 

I close the issue, since I think it's not a real issue.
