### ISSUE TITLE
[V8] product_variant_default_code, when internal referrence product template in form id filled, i lines of variants missing attribute code

### ISSUE THREAD

**Issue by bunhin** [odoomrp/odoomrp-wip#1284]
Fill Internal Reference mask for variants code
Fill Internal Reference for product template
save to generate variants
1 line of variants (first line) the default code generated not according to the mask but take the internal reference for product template as variant code (internal reference)

if internal reference for product template not filled (empty), the default code of product template is same with one of variants code

Wanted the code of product template should not same with any variants code, actually want the code for product template become prefix for the variants code, the module works but have above issue, if variants default code all are right, the default code for the template become not right (become same with one of the variants code)

**Comment by anajuaristi** [comment]
That's not an error but the expected behavior. You need to set attribute
names on product template code field to obtai  different code names for
products. Otherwise all variants will have  same name
Example: mask = prefix_[color][size]Will code products as
prefix_whiteXL
prefix_blackXL
Plain text on mask will be taken as plain text on variants code

**Comment by bunhin** [comment]
Dear Anajuaristi,
Thank you for your response, but i am sorry not get your point yet. Please let me explain in more detail:
Create new product template  : Name =  GW T-Shirt
Put in internal reference mask field  (for variants i expect) =  VGW151A-[Size]
Put in internal reference field (for template i expect)          =  GW151A
add attrivete Size with attribute value added = 95, 100, 110, 120, 130, 140
Then save and variants is generated
I expect for product template [code] Name = [GW151A] GW T-Shirt
I expect  for variant code to be;
VGW151A-95  this for size = 95
VGW151A-100 this for size = 100
VGW151A-110  this for size = 110
VGW151A-120  this for size = 120
VGW151A-130  this for size  = 130
VGW151A-140   this for size = 140

Actual variants that are generated;
GW151A    this for size = 100       is this not an error?  for my view  is an error, expected =VGW151A-100    not   GW151A

VGW151A-110  this for size = 110   this is and bellow are correct 
VGW151A-120  this for size = 120
VGW151A-130  this for size  = 130
VGW151A-140   this for size = 140
VGW151A-95 this for size = 95

It seem for the first variant line  (size value code = 100   that is listed firts  comparet to size 95) not following the prefix stated in "internal reference mask"

Could you please re check,  and correct me if has have wrong input or expectation.

Thanks,
Bun Hin

**Comment by anajuaristi** [comment]
Don't set internal reference field on product. Only "formula" on mask.
Module has got an utility allowing you to set values manually on variant
code. The variant you menction is probably the first one created for that
template. If you fill the code field manually it's probable the code
generator doesn't  update it.

El 22/8/2016 14:16, "bunhin" notifications@github.com escribió:

Dear Anajuaristi,
Thank you for your response, but i am sorry not get your point yet. Please
let me explain in more detail:
Create new product template : Name = GW T-Shirt
Put in internal reference mask field (for variants i expect) =
VGW151A-[Size]
Put in internal reference field (for template i expect) = GW151A
add attrivete Size with attribute value added = 95, 100, 110, 120, 130, 140
Then save and variants is generated
I expect for product template [code] Name = [GW151A] GW T-Shirt
I expect for variant code to be;
VGW151A-95 this for size = 95
VGW151A-100 this for size = 100
VGW151A-110 this for size = 110
VGW151A-120 this for size = 120
VGW151A-130 this for size = 130
VGW151A-140 this for size = 140

Actual variants that are generated;
GW151A this for size = 100 is this not an error? for my view is an error
VGW151A-110 this for size = 110
VGW151A-120 this for size = 120
VGW151A-130 this for size = 130
VGW151A-140 this for size = 140
VGW151A-95 this for size = 95

It seem for the first variant line (size value code = 100 that is listed
firts comparet to size 95) not following the prefix stated in "internal
reference mask"

Could you please re check, and correct me if has have wrong input or
expectation.

Thanks,
Bun Hin

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/odoomrp/odoomrp-wip/issues/1284#issuecomment-241395189,
or mute the thread

**Comment by bunhin** [comment]
Dear Anajuaristi,

Yes, if i do not fill the "internal reference" field in product template and only fill the "internal reference mask" field during creation, all variants have code generated correctly, but the display for the product template (list or form view) taking the first variant code   [first-variant-code] Product template name  
something like 
[VGW151A-100] GW T-Shirt
6 variants

instead, i expect to be: 
[VGW151A] GW T-Shirt
6 variants

in other words,
if the  mask ="VGW151A-[Size]"  with size value = 95, 100, 110, 120, 130, 140, i expect:

[VGW151A] GW T-Shirt
6 variants

and the variants internal reference:
VGW151A-95
VGW151A-100
VGW151A-110
VGW151A-120
VGW151A-130
VGW151A-140

for all variants now are have correct code generated as expected above (if we do not fill anything in the internal reference field of product template),  but the product template display then taking one code of the variants. 

[VGW151A-100] GW T-Shirt
6 variants

is this normal?

quote
"Don't set internal reference field on product. Only "formula" on mask. Module has got an utility allowing you to set values manually on variant code. The variant you menction is probably the first one created for that template. If you fill the code field manually it's probable the code generator doesn't update it."
unquote

**Comment by anajuaristi** [comment]
Yes. It is. Because template itself "doesn't" exist. The form view is
always showing a product and fields for both tables are mixed on it. It's
because of that you see the field filled.
Most of the times is not easy to identify the updated table when you change
a value.

**Comment by pedrobaeza** [comment]
@anajuaristi, look at this issue that mentions something similar: https://github.com/odoomrp/odoomrp-wip/issues/761
