### ISSUE TITLE
[8.0][mrp_final_product_lot]Possible bug when used with mrp_byproducts

### ISSUE THREAD

**Issue by AntMoreno** [odoomrp/odoomrp-wip#1373]
Good day

Steps to reproduce

- Install mrp_byproducts checking option "Produce several products from one manufacturing order" in Settings -> Configuration -> Manufacturing
- Create a BoM for a "Product A" that will consume "Product B" and will also produce "Product C" as subproduct.
- Launch a Manufacturing Order for "Product A"

Current behaviour

- mrp_final_product_lot creates in stock_production_lot only the lot for "Product A", but creates quants for both "Product A" and "Product C" linked to the same lot_id of "Product A".

Expected behaviour

- mrp_final_product_lot should create lots for both "Product A" and "Product C", since both are final products of the order. It also should create the quant of "Product A" linked to the lot_id of "Product A" and the quant of "Product C" linked to the lot_id of "Product C".

Thank you

**Comment by anajuaristi** [comment]
It's not an error, since the lot-number/lot-name is defined by product and it can be changed manually when you want.  
System is creating a lot number for product A and lot number for product C. It's not posible to be the same lot id since the relationship between lot and product is many2one. It's creating 2 ids with the same name, related each one to a different product 
If you take a look to internal lot_id, for sure, they are 2 different Ids. You can set the name you want to each one.
I close the bug since from my point of view, it's not a bug but expected behavior.

**Comment by AntMoreno** [comment]
Hello Ana, thank you for your prompt reply.

I think maybe I didn't explain very well, maybe due to my poor english ;)

Precisely I don't expect the system to create the same lot number, I expect it (and supposed it was going to) create two different lot_ids, one for each product. Yes, with the same name, thats ok, but they should be two ids (records) in the stock_production_lot model. Actually the addon is creating just one lot id, not two as you say, in stock_production_lot, and two quants in stock_quants. So if you think, as I do, that there should be created 2 different lot ids for Product A and Product C, then there's obviously a bug.

A way to understand the problem that produces the current behaviour is to make a manufacturing order as described, and then once produced and with lot created (say lot AAAA) try to make a picking of product C with lot AAAA. In the transfer details form you won't be able to select the lot AAAA because that lot was only created for Product A, and the drop-down lot list can't show it since it doesn't exists for Product C.
