### ISSUE TITLE
[8] when run procurement plan, does not take into account the stocks before making procurement

### ISSUE THREAD

**Issue by mauroanelli2017** [odoomrp/odoomrp-wip#1411]
it creates purchase order, regarding i have the products or not

**Comment by mauroanelli2017** [comment]
any development?

**Comment by anajuaristi** [comment]
No. That module is not very often used by our customers because it was built following specific requirements for one of them, so changing or adding anything is not included on our roadmap

If you want to try yourself and make a PR or to build and extension module that complements what we already have. 

Thank you.
Ana

@Daniel-CA you can close
