### ISSUE TITLE
Question about machines and workcenters

### ISSUE THREAD

**Issue by clonedagain** [odoomrp/odoomrp-wip#400]
Hi,
I just noticed @anajuaristi linked the OCA requirements about machines to the module `machine_manager`.
Can you please explain why this needs to be a new distinct `Model` rather than extending the existing `mrp_workcenter` `Model` ?
I have some of these requirements too and I'd like to evaluate options before moving forward.

**Comment by anajuaristi** [comment]
Hi:

It's needed because a company could need having registered their machines data even if this machines are not related to manufacturing 

Take as example, computers, microscopes, measure takers and so on. Machine is much more generic than workcenter and could be used by any company even if they not produce theirselves.

We made 2 more modules to link machines with purchases and assets.
