### ISSUE TITLE
module name

### ISSUE THREAD

**Issue by bealdav** [odoomrp/odoomrp-wip#431]
Why some modules have plural form like mrp_production_notes, mrp_bom_notes, etc. ?

Ok there are several notes, but if you have done a module it's to manage several items.
And 'sale' module also have several sales. 

Singular is easier in all cases. Module machine name should be singular and module display name could be plural as it in the image

![note](https://cloud.githubusercontent.com/assets/1853434/5393738/240d218e-8135-11e4-8db8-f7e7269c1336.png)

Could you consider a rename of these modules ?

My 2 cents

Thanks a lot for your huge contributions on mrp

**Comment by pedrobaeza** [comment]
Hi, David,

The general criteria used for naming modules is the following:
- **Name of area**: for example, mrp, or sale, purchase, etc.
- **Name of object inside the area**: In this case, production (which is already called as mrp.production inside Odoo).
- **Function or modification done**: This is the most irregular part of the name, because it depends a lot on the functionality of the module.

Said that, for this case, we always think the name as the relation with the main object. In this case, you put some notes (in plural) for a production order. That's why we call it mrp_production_notes. It's true that all notes goes to only one field, but semantically speaking, they can be more than one (each paragraph can be a note).

I think this is the same reason why Odoo call mrp_operations module with plural (or simply laziness :stuck_out_tongue:)

If you think it's better name _mrp_production_note_, we can rename it without problem. We are not yet in production in any environment. That's why we put this repository. When we consider a module mature enough, we pass it to odoomrp repository or directly to OCA.

Thanks for your comments. They are appreciated.

**Comment by sebastienbeau** [comment]
Hi Pedro,
Personnaly I prefers to use 'mrp_production_note' even if we can have several note as it's a paragraph. I think it's better to always use singular, so we don't have to ask ourself when updating a module if the module need a "s" or not, same when we add dependency, it's simplier to always use singular.
I will be great to have opinion of other people (let's send a tweet on this ;) )
Thanks

**Comment by pedrobaeza** [comment]
OK, I don't have a strong opinion on this, because you know each mind goes on its way ;)

**Comment by sebastienbeau** [comment]
Yes until we do not have real convention it's hard to have a name that fit with everyone, let's see what other think ;)

**Comment by anajuaristi** [comment]
I vote notes instead note. Maybe on the rest of fields is better singular but just in note, I don't see note but notes... I don't know why

**Comment by bealdav** [comment]
I'am ok than 'note' can appear weird, but consistency (and easy practices) seems to be more important than taste. 98% of the modules are in singular form and 99% of the 2% are in error (yes 'mrp_operations' you are in this case) if you consider the rule for main modules: purchase, sale, product, account, etc.
my 3 cents

**Comment by yvaucher** [comment]
As even official module `note` is singular, I think technical name for other modules should also be singular.

Technical name should be as short as possible and as said we already have almost all modules in singular so my vote is for `note`.

**Comment by jgrandguillaume** [comment]
I also join Yannick here to have note as singular, like original module name

**Comment by pedrobaeza** [comment]
OK, thanks for your comments. I will rename it ASAP.

Taking the occassion that all of you will receive notifications, we are going to start publishing modules to OCA. One question is where to host quality control modules. I don't see any repo that can host them.

**Comment by bealdav** [comment]
@pedro and all mrp-wip contributors: thanks for this incredible work of spanish community mainly.
But before to send these module in OCA:
If mrp_production_notes must become mrp_production_note, what is your position about other modules in plural form.
In fact I don't understand why some are in plural other in singular: examples
stock_picking_taxes => stock_purchase_unit
stock_move_purchase_price => sale_order_recalculate_prices
product_type => sale_order_types
quality_control_tolerance => quality_control_samples
crm_claim_links => mrp_project_link
...

Is it consistent in each case ? Isn't it an headache to know which are ok which are not ? How to keep all this in my small memory ?

@jgrandguillaume, @max3903 : what OCA think ?

Thanks

**Comment by sebastienbeau** [comment]
Hi, thanks @pedro for you're great work ! Long live to odoomrp !
I agree that we should get a consistency and only have singular name in the module. It's easier to remember, are you ok to rename all the following modules (stock_picking_taxes, stock_picking_taxes,  sale_order_types, quality_control_samples, crm_claim_links).
Sorry to bother you with such a detail, but we already make the mistake by calling 'product_imageS' a module and I always forget the 'S' when I run an update. I am pretty sure that I will use and contribute on our module so this is why I care about avoiding my "futur-sebastien" to have headache ;)

Thanks for your great work !

**Comment by pedrobaeza** [comment]
Thanks for your thinkings. In some cases, the name it's going to be weird, but I agree that we need consistency. The only one that I'm going to keep is mrp_operations_*, because upstream core is called that way.

**Comment by gdgellatly** [comment]
Hi,

David asked me to take a look at this thread.  imo Pretty much what Pedro said above.  Leave operations, singularise the rest.  The only consistency you will ever find in Odoo code is inconsistency.

**Comment by anajuaristi** [comment]
I'm closing this issue, since modules has been renamed

**Comment by bealdav** [comment]
@anajuaristi @pedrobaeza thanks for the rename campaign. It brings homogeneous convention.
But it seems some other modules are in plural form: base_partner_references, crm_claim_links, mrp_bom_through_attributes, mrp_product_variants_... (3 modules), mrp_product_real_costs, mrp_product_type_views, ....

Is these module should becomes OCA modules ?

Thanks

**Comment by anajuaristi** [comment]
@bealdav 
Yes if OCA accepts them. 
By now we can not afford the task of renaming all that modules. Just renaming all "notes" modules has been a really headache.because some of our customers are using them in production environments
Maybe on the moment they are published on the OCA we could go one by one renaming them but not during the time they are on OdooMRP branch

**Comment by anajuaristi** [comment]
@bealdav About the modules you are mentioning
Most of them must be plural.

base_partner_references: it's adding several references on partners form
crm_claim_links: it¡s creating several links on claims/pickings
mrp_bom_through_attributes: Bom is looping though all attributes of a product.

The name must be plural on this cases...

**Comment by bealdav** [comment]
@pedrobaeza @anajuaristi, you're right, rename is an headache without this tool https://github.com/bealdav/erp_rename.
Avoid plural is just to win time when you write dependency on other modules. 
Developers are not spell and semantic perfectionist and make a lot of errors with plural. Some of us, like me, have small memory brain and remember where 's' is a nightmare. 
The name in the **openerp**.py could be have plural if you want.
End users don't have to know technical names

I will close debate, you know my opinion: make erp developers more productive to make an efficient application in the future and remove wasting time details

my 2 cents

**Comment by anajuaristi** [comment]
@bealdav I agree with you but.. believe me. Sometimes perfectionism is figthing directly with productivity.
There is another opinion for developers: If something works, please don't touch it :)
Thank you for the debate. It has been very interesting.

**Comment by yvaucher** [comment]
@anajuaristi I disagree, inconsistencies is often a pain when you are developing. And the spirit in open source is if I find an issue I report it and improve it. Contrary to proprietary software we do have resources to fix little things and I think it's worth it instead of letting more and more little things raised.

**Comment by bealdav** [comment]
sorry @anajuaristi but +100 @yvaucher 
I learned since 3 years at akretion and with OCA contributions to become perfectionist on code: myself, with my 15 past years as only functionnal guy (not on code). It's possible for developers to become perfectionist on code.
But it's impossible for developers to become good at spelling and writing (some of them are killer in code but poor in spelling, that's ok like that). Please make developers life easier. 
and yes "inconsistencies is often a pain when you are developing".

At akretion (and at OCA) we don't share "If something works, please don't touch it" opinion. Step by step we improve our work, make it generic and reduce the number of lines to be easier to maintain
Thanks to all OCA guy for their advices on this matter

**Comment by anajuaristi** [comment]
Inside me I agree with you but sometimes, we (functional people) are the
ones that stay in front of the customer
And... even if you heavily test any change is a risk when they are in
production. It's quite hard to explain... your proccess is not working
because developpers changed something just to be easier to mantain.
Developpers ask us to understand it's easier for them but they also should
understand us :)

At the end, I don't take technical decisions but only I'm afraid of
fighting with customers about things that they don't understand and
worst... they don't mind because they only want their proccesses working!!

This is really a very complex world

Thank you everybody

2015-07-16 11:48 GMT+02:00 David Beal notifications@github.com:

> sorry @anajuaristi https://github.com/anajuaristi but +100 @yvaucher
> https://github.com/yvaucher
> I learned since 3 years at akretion and with OCA contributions to become
> perfectionist on code: myself, with my 15 past years as only functionnal
> guy (not on code). It's possible for developers to become perfectionist on
> code.
> But it's impossible for developers to become good at spelling and writing
> (some of them are killer in code but poor in spelling, that's ok like
> that). Please make developers life easier.
> and yes "inconsistencies is often a pain when you are developing".
> 
> At akretion (and at OCA) we don't share "If something works, please don't
> touch it" opinion. Step by step we improve our work, make it generic and
> reduce the number of lines to be easier to maintain
> Thanks to all OCA guy for their advices on this matter
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/431#issuecomment-121908607
> .

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

_El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Klara Donea 13, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
*_administracion@avanzosc.
soporte@avanzosc.eses*

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: *_Klara
Donea 13*\* 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 - *
_administracion@avanzosc. soporte@avanzosc.eses_ _This message and all
documents attached to it are confidential and intended only for the person
or entity to which it is addressed. Any use of this information by
unauthorised persons is prohibited under current legislation. If you
received this message by error, please advise us, destroy it and refrain
from communicating its contents to third parties. We apologise for any
inconvenience receiving this email improperly may cause to you. Your
personal data are included in a file owned by Avanzosc, S.L. If you want to
exercise your rights of access, correction, erasure and objection you can
contact the Controller at *_Klara Donea 13*\* 20720, Azkoitia (Gipuzkoa), T:
943 02 69 02 – administracion@avanzosc. soporte@avanzosc.eses*
