### ISSUE TITLE
Machine users: This should be linked to hr and not to user

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#490]
Many machine users in producing companies are not using the ERPs. So to force to have a user created to assign a machine does not reflect the reality of the field.

To be able to use a HR employee instead would be more realistic.

Further, many pricing options are linked to the number of users. Therefore many companies will require to have the link to hr and not to user to not multiply the number of users.

**Comment by anajuaristi** [comment]
This is a discussion point.
In Odoo, you can have users that are not employees and employees that are not users. So using one or another in any model of system is related to after needs.

In our case, we followed the rules of Odoo standar itself where when assigning people to a task, project, crm case... etc the used model is "user" itself and never employee so we considered better doing like that. 

Thank you for your proposal but we could consider it as whishlist and not a bug.

**Comment by pedrobaeza** [comment]
It's not even a wishlist. It's simply a different approach, but both are incompatible. As Ana said, we have taken the Odoo approach, and this means that maybe you have to create some "fake" users to reflect some workers, but it's a minor problem, because you can control their login status with active field.
