### ISSUE TITLE
Product variants

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#492]
1. No automatic variants: Should be positive. Automatic variants and then yes, no, based on category value
2. Field required should be after the attribute. Otherwise, it is not understandable.

**Comment by anajuaristi** [comment]
1. We can't do it like that, since the standar Odoo option is creating all variants. We are avoiding that creation and user must specify "don't create"... It's conceptual. I don't know how to change to better understanding.
2. I don't see the difference having it before or after. It's just the same.

**Comment by pedrobaeza** [comment]
I agree with Ana in the concept that by default, variants are created, so what you want is to force not to create them. If you make the contrary, someone can think that the added module is the one that creates variants.

The second change can be considered, but it's not very important, because each one has its own "understandable" standards.

**Comment by ybofr** [comment]
It is always complicated to have something negative to agree upon. DO NOT CREATE: yes. This is complicated for the user. This is all was referring too. Basically, it does not seem to me like a big change, but from the user point of view more understandable.

The point of having the required before or after is that the user defines first the attribute, then he decides to make it mandatory. It's just more about the usability. Most people read from left to right, so they will ask themselves what they have to put in the field required without even having defined the attribute. Again, it's only usability, not a bug.

I believe, many users will not have your experience in the system and we should think about it, when we design the screens. Small details like that can make the system appear more complex as it is really.

**Comment by ybofr** [comment]
Another proposal: "block automatic variant creation". This way, you still can let the rest as it is.

**Comment by pedrobaeza** [comment]
About first point, I don't read it like that, because you don't have a dropdown asking you "Yes or no", but a checkbox to mark "Don't create". If you check it, then you are enabling the verb of the checkbox. You have some examples of this use on Odoo standard, with the checkbox "Don't use sale teams" as a per user selection.

About the second one, I have changed it on https://github.com/odoomrp/odoomrp-wip/commit/64f6861cc915cea789b91d16b1109a5a09d7c679, because it's a small detail and it can be more comprehensive as you say.

**Comment by pedrobaeza** [comment]
What about "Don't create variants automatically"?

**Comment by ybofr** [comment]
Pedro, in the version I use, there is no checkbox, but a dropdown list. This is probably the reason I did the remark in the first place. With a check box, there is nothing to change. It's perfect.

**Comment by anajuaristi** [comment]
It can not be a checkbox because we have got 3 options Yes, no and "take from category"

This 3th option makes no possible having a checkbox. The idea is that you could set by default "take form category" so, you don't need to remember on each product if variants should be created automatically or not, just review categories and it will be same choice for all products inside that category. 
About  "Don't create variants automatically" or "block automatic variant creation" I agree it's more comprehensible for user. 

About moving required, after atribute values, it would be also ok and it's not big change on module.

**Comment by pedrobaeza** [comment]
I have improved the overall labels and defaults on https://github.com/odoomrp/odoomrp-wip/commit/02ae35a4911e412a6d99cafdca45a70cb9b69699:
- At product level, selection values are now: 'Create them automatically', 'Don't create them automatically', 'Use the category value'
- Label for this selection is 'Variant creation'
- Default value for product selection is to use the category value.
- At category level, label is now 'Don't create variants automatically'.
- Default value for this check is to be marked.

**Comment by ybofr** [comment]
This is cool. Thank you very much
