### ISSUE TITLE
Creation of the routing

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#498]
Create routing / workcenter operations / Operation
1. In many productions, to maintain information in hours is not realistic as some operations only take 1 or 2 minutes. So many production managers are used to see the information in minutes and not in hours (But in the end, this is an ideological choice)
2. Many people (like me, user lamda) will be confused by the fact that in the detail of the operation, you enter the time in hh:mm and on the overview screen, the time is recalculated to appear in hours only. It forces the user to make calculations if he wants to see that the data is correct.
3. There is no link between the work centre info lines on the operation and the number of hours that is mandatory. This makes it a little bit confusing to understand how much time will be used or which of the workcenter information or of the general operation will be used for planning.

**Comment by anajuaristi** [comment]
@pedrobaeza 
I think points 1 and 2, it's just field format. Could it be easily changed to show hh:mm:ss instead of only hh:mm ? 

@ybofr when you say overview screen on 2, What do you mean? what screen? I see number or hours in hh:mm format in form and tree view on routing. I don't see the difference.

About 3. I don't understand very well what you mean, but, there is a field number of hours directly on routing step. It's true we did not include on machine/routing line relation where there is another efficiency parameters. 

As it's stimated hour cost, and system will allow specifying the real expended time to make an operation, we thought it was not necesary fixing for each machine. It's true that maybe it would be good enhancement. Curiously noone of our customers asked for it. 

@pedrobaeza Opinion about @ybofr sugestion?

**Comment by pedrobaeza** [comment]
1. You can also put the time in minutes, because the widget allows it. The only consideration you have to take is to type `:` before the minutes, and the conversion will be done. For example, `:187` will be converted to `3:07`.
2. It's true that for the tree, hours appear as float instead of the time visualization, but this is part of standard Odoo. @anajuaristi, please fill an issue and use maintenance contract for that being fixed. The problem is here: https://github.com/odoo/odoo/blob/8.0/addons/mrp/mrp_view.xml#L240, that must put `widget='float_time`.
3. Ana, this is not what Eva is saying. She is saying that you can set specific times for each work center, but the other time (for operation) is unconnected with this information. We can make 2 things: a) hide times at operation level (and let the ones at workcenter level), or b) calculate operation time as an average of work center times.

Another issue I have faced seeing this one is that the label of the workcenters shouldn't be "Workcenter Info Lines", but "Possible work centers for this operation".

**Comment by ybofr** [comment]
@pedrobaeza: ok, I guess, this is what I thought. Did I understand it properly, that for the very routing, you can then define the workcenter by pressing "default".

**Comment by pedrobaeza** [comment]
Default is used for pre-selecting that workcenter when making a manufacturing order with that route.

**Comment by oihane** [comment]
I've made some changes according to this

In tree view now you can see `hh:mm` `widget='float_time'` has been put in the view
And related to the issue #500 and as it is also commented here, when yo push "default" in the line it changes the workcenter, if there are more than one it gives a warning, althought it does not erase the selected default, when you save it, internally it fills the workcenter and erases other defaults.
All these changes have been made in PR #542
