### ISSUE TITLE
Create a routing: Defaults in work center info line are not mutually exclusive

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#500]
Manufacturing/routings/create routing/Create operation
If you select default on two different lines, they are not mutually exclusive. An error message just appears telling that a default already have been chosen.

**Comment by pedrobaeza** [comment]
I don't see that default option that you mention. Where it is?

**Comment by ybofr** [comment]
I mean the work center info lines.

**Comment by anajuaristi** [comment]
Yes, on routing lines / workcenters list there is a check default 

Usability on this point can be easily improved. This message should be avoided:
"There is another line set as default, disable it first."

On checking one workcenter by default system should make false the others without having to ask to user. 

This issue was reported internally a few weeks ago but it has not been repaired by now. 
@Daniel-CA please take care of it

**Comment by ybofr** [comment]
So, I close the issue?

**Comment by oihane** [comment]
No. We will close when it is fixed.

**Comment by oihane** [comment]
@pedrobaeza this was going to be fixed in #538 but I think that it still continues as @ybofr said, I'm going to test again and to try to fix it.

**Comment by oihane** [comment]
Solution has been merged so I close this issue
