### ISSUE TITLE
Project is mandatory in the manufacturing order

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#503]
Why is project a mandatory field in the manufacturing order?

**Comment by anajuaristi** [comment]
This is mandatory if you have got installed costs modules. 
We collect all estimated and real costs in analytics so we need an account to assing to analytic lines.

Idea is that a project can contain several MOs and collect costs of all OFs. 
There is no way to make project not mandatory if users wants to collect costs, otherwise if he doesn't want to collect them just don't install costs modules.

I close the issue since it's a question

**Comment by ybofr** [comment]
Hi Ana,
I believe, for you as an Odoo expert, the terminology is clear. If someone is not an Odoo expert, he will not understand why he needs a project to have the costs, so I propose to change the term project to "analytic account". This way, everyone will understand it.

**Comment by anajuaristi** [comment]
It's not the same and we can not use analytic account on this case.

In Odoo When you create a project, automatically is created an analytic account and that's ok.
But, when you create an analytic account could be that there is no project at all and that's also ok.

In production, we are using all human resources and project tasks wizards to allow manufacturing operators to include their expended time working in an operation / OF. 
They work against a task so a project is needed. We are collecting costs in related analytic account but tasks for operators are created on assigned project so we need the project, not the analytic account. We can not change the name on this case.

**Comment by pedrobaeza** [comment]
Maybe we can name it 'Production project'?
