### ISSUE TITLE
Create BOM/activate: Confirmation message is not understandable

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#629]
"Confirm MRP BoM activation
You will activate the LdM, If you have not set a route, you can not put. Are you sure you want to proceed?"

What is LdM?
What does "you can not put" mean?

**Comment by anajuaristi** [comment]
@ybofr for sure that's a new language named spanglish. LM in spanish is BOM.
Yes, message it's wrong. It want mean something like... You are going to activate a bom. If you did not set a route you could not set it after (even this one would be wrong, since on last module version we are allowing to set to draft so you could set anything after activating)

**Comment by pedrobaeza** [comment]
Fixed on https://github.com/odoomrp/odoomrp-wip/commit/ed449bb75f9157586a61aa686a5968717e6efdfe
