### ISSUE TITLE
mrp_project_link. Really needed?

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoomrp/odoomrp-wip#649]
Hello!

I'm reviewing your work, as part as an effort to establish an engineer-to-order process. I don't see why you need to replicate the work orders associated to manufacturing orders to project tasks. 

In my opinion they are separate areas. In projects, you normally first define your tasks, then sequence them, estimate the effort and resources. Then execute the project as per the plan. 

During the execution of a project you may create a manufacturing order that would alter the plan by created unplanned tasks.

In case that the reason was for the convenience of entering time, you might be interested to look at the following modules that I just published in https://github.com/Eficent/project-manufacturing-wip.git:
mrp_analytic
mrp_workorder_line_work
mrp_workorder_line_work_timesheet

Perhaps this can help you see it from a different perspective. And also can help me understand your motivation for the approach that you followed.

PD: Your work on odoomrp is really great. I'm looking forward to finding opportunities to collaborate!

Regards,
Jordi.

**Comment by anajuaristi** [comment]
We DO NOT replicate work orders on projects. :)

Let's say our vision is similar to yours. For us, full Manufacturing order is a single taks on project. So... you can have just tasks without being linked to a manufacturing order but you can have a task that it's a manufacturing order per sé. 

About work orders --> You are right it's not necesary duplicating them and we are not doing so but... there are operations/work orders where more than one operator must work. So... in that case (only in that case) where each operator has to register times and could have a fixed planned time to do the task, we create "derivated tasks" that are "child tasks" related to the manufacturing order tasks (so it would not modify the planning just because chind tasks are subtasks of primary one)

This way we are allowing to have manufacturing integrated with projects, on standar way and in the other side we could plan inside the project not only ingeneers work but also manufacturing operators. 

About your modules, I think they are not at all incompatible with ours, just because we add OF and OT on analytic line, so... if you allow directly reporting time on OT by any worker... that's an extension to OdooMRP, it's just extending our vision. We should try and let you know. 

Thank you!!

Ana

**Comment by JordiBForgeFlow** [comment]
Thanks Ana,

In case of operations in manufacturing orders where you want to keep track of hours by each operator, I was thinking of introducing more fine-grained work centers (for example, 1 WC per operator), and then having more operations in the routing. If 1 WC = 1 operator, then you would not require to create a child task in Projects.

What I have in mind are two possible scenarios to integrate Projects with MRP:
A) Treat manufacturing  as a 'service' requested by the project, completed by the manufacturing department. A "Manufacturing BOM" is defined, listing all components of the product, and structured to show production people how to put the product together (has all the operations contained in the routing). The work centers in the manufacturing dept. complete the MO as per what is defined in the work orders. This is useful in scenarios where the manufacturing dept. tends to work on 'modularized' products that can serve multiple projects.

B) Treat manufacturing as an integral part of the Project, where the Product that is created is also unique to the Project. In that case, engineering department creates a BOM as an "Engineering BOM". This BOM is the last step in engineering design. It is the engineer's way of telling the rest of the organization how many of which components make up a product.  Then, the tasks required to complete the Product are defined as part of the scope of the project (because the product is unique to the Project). In that case, the result of the manufacturing order is a WIP product which value does not include the labor that was required to produce it, but just the sum of the components. The value of the Product is not realized by the product #, but by the outcome of the project delivered to the customer (that may involve not only the assembly of parts, but also the testing, training, etc..).

So the question to be addressed during the planning stages of the project is whether you are willing to use approach A or B (or both?).

Then, in my case I first create the Tasks, and then define the products that are required to complete it, together with the estimated labor. You then get approval on the Project Plan before proceeding with Execution.

During the Project Execution, you initiate the procurement for the products that were planned in the Task. Some of the procurement may end up in manufacturing orders, and other times in PR's or PO, but then, you see that first is task planning, and then MO's come next, not vice-versa.

The concepts of "Manufacturing BOM" and "Engineering BOM" are introduced in the book "Orlicky's Material Requirements Planning", and also described here: http://en.wikipedia.org/wiki/Bill_of_materials

Regards,
Jordi.

**Comment by anajuaristi** [comment]
Again, your vision is not incompatible with ours
If you want to define a WC by operator and include more steps on routing you can do it, just creating them as you want and marking "operators needed = cero on workcenter operator". This would avoid creating tasks on projects for operators, so you don't need making any aditional development to configure this case.

About materials... I think both aproaches you propose could be supported by OdooMRP. 
We added /linked purchase orders to projects, and we also did for procurements so you can first make the list of components you need for a project and after that consume in an MO 

Or you can do inverse way first define BOM (we allow having dinamic boms and specific boms so I think also your "engineering bom" where not all especific materials are needed to be fixed from begining is also covered.

At the end, you will launch one or several manufacturing orders that could be or not included in a project. And you could have several projects/subprojects with tasks that could contain or not manufacturing orders. 

We tried to do it as generic as posible to allow covering any situation but... it could be there is still some automations or decisions that we did not take in mind. Could be... always.. 

Thank you for contributing with your comments!!!

**Comment by JordiBForgeFlow** [comment]
Thanks Ana. I'm trying to understand it, so as to attempt to contribute where possible. Best if we join forces to make a better product!

When I referred to "engineering BOM" I was referring to the breakdown of parts only (excluding the task to complete). I'm not too familiar for now with dynamic and specific BOMs, but I've seen the videos and it looks very powerful!

I will continue to review your work, and will let you know my comments. 

Thanks!! :)
Jordi.

**Comment by anajuaristi** [comment]
Yes!! engineering BOM can include only breakdown parts... but also you can configure the process using routing. And... the great thing is that you don't need knowing exactly the product you are goint to use in a BOM level but you need know it just before launching the order. Meantime you can go configuring different levels, with templates (generic templates) and you could even create one draft MO with template products that you will substitue just when you really need launching the MO, not before.

I think this functionality is not given by too much manufacturing solutions on market and it has been possible due to Odoo's template/product aproach and our manufacturing configurator feature. 

Please take a look: https://www.youtube.com/watch?v=D8mUZ9hT7hE
