### ISSUE TITLE
Subcontracting - usability suggestions and questions

### ISSUE THREAD

**Issue by StefanRijnhart** [odoomrp/odoomrp-wip#658]
Hi,

first of all, thanks for the great work!

I have an interest in MRP subcontracting. I watched the Spanish video on http://odoomrp.com/blog/blog-noticias-1/post/nueva-herramienta-para-la-gestion-de-operaciones-de-subcontratacion-en-procesos-industriales-6 and was able to reproduce the results.

Except in my configuration, I have one problem with the subcontracting product. I think the video mentions that this best be a service type product. But this prevents the procurement of the product to run, which is as I expect Odoo to work. It seemed to work in the video, so maybe there is a module or a setting that I am not aware of. As I am now using a regular product, my stock location fills up with these operation products that I don't really have.

Other than that, I noticed some usability issues that I would like your opinion on. If you agree, I may be able to file some PRs.
- Outgoing picking does not have the outsourcing partner on it.
- Source document (reference) of the outgoing picking and purchase order of the subcontracting service could be the MO number instead of (only) operation + product
- Integration of with work order line would be useful: transferring the incoming picking currently does not complete the subcontracting work order line. Plus the user can complete it independently of the incoming picking, almost unnoticed. It would be nice to have another state 'waiting', maybe with the option to force the operation instead of just finishing it (with a nice red alarmistic icon). Relatedly, a chatter message on the related MO saying the halfproduct has returned from the external operation would be nice.

What do you think?

**Comment by anajuaristi** [comment]
Hi @StefanRijnhart 

It's a pleasure to see you here in OdooMRP project!! 

I will try to explain your questions

When you say: "this best be a service type product". Yes, usually the subcontracting product is a service so we need having purchase order (service) incoming picking(semielaborated) so... as we need also semielaborated product to controll reception from supplier we can do single step and control everything if we define stockable or consumable instead of service. So we recomend semielaborated not to be services. 

About your points:
.- Outgoing picking does not have the outsourcing partner on it --> It should have. This is a known bug that I thought it was corrected. Outgoing picking partner should be set for same supplier when purchase order is created. Before that, we don't know selected supplier to make the job. 

.- Source document (reference) of the outgoing picking and purchase order of the subcontracting service could be the MO number instead of (only) operation + product  --> Totally agree. Good point. It would be nice enhancement to be included

.- Integration of with work order line would be useful: transferring the incoming picking currently does not complete the subcontracting work order line. Plus the user can complete it independently of the incoming picking, almost unnoticed. It would be nice to have another state 'waiting', maybe with the option to force the operation instead of just finishing it (with a nice red alarmistic icon). Relatedly, a chatter message on the related MO saying the halfproduct has returned from the external operation would be nice --> Also agree. Another good point. 

About PRs It would be great if you could include these enhancements on subcontracting module but we could also assign someone from our development team. Please, let us know.

@pedrobaeza please take a look to stefan's proposals

Thank you!!!

**Comment by pedrobaeza** [comment]
Hi, @StefanRijnhart,

> - Outgoing picking does not have the outsourcing partner on it.

Fixed in https://github.com/odoomrp/odoomrp-wip/commit/b4b3fc9bd2b101ef2e2e4ee880446da19ac3a88a

> - Source document (reference) of the outgoing picking and purchase order of the subcontracting service could be the MO number instead of (only) operation + product

Fixed in https://github.com/odoomrp/odoomrp-wip/commit/612210a96251ee528dc406e1a04c3d0d5ebaaad3

**Comment by pedrobaeza** [comment]
The last point is in progress.

**Comment by StefanRijnhart** [comment]
Thanks ;-)

**Comment by anajuaristi** [comment]
Just to let you now: 
Recently we published a module that allows service type products to create a procurement. 

I'm closing the issue, since the 3th point is not an issue but enhancement. If it's really needed we will  open a new one.
Thank you!!

**Comment by sotolucas** [comment]
Hi,
first of all thanks Ana and Pedro for your huge work and sorry for reopening but i'm stucked as many people with this issue and i'm very frustrated.
In a punctual case I have a part that is made from a pipe (raw material) and a subcontracted service (lathe machining). Odoo checks if pipe is or not on stock, and if it's not on stock generates a RFQ (Routes Buy + Make to Order)... As you suggested I installed the module procurement_service, so I can now select Routes for Service type products but... Buy + MTO routing is not working for Lathe machining.
At this point the generated procurement is in execution state but nothing has been generated.
Maybe i'm missing something? 

EDIT: I'm not recieving a semielaborated. I recieve the finished part just ready to be used... Just in this case, that's why I need the semi to be a service. Sometimes I recieve a semielaborated and then I need to galvanize it, for example.
