### ISSUE TITLE
Cannot manually create any product variant

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#766]
Hi,

The module is great, and it works perfectly to create product variants based on confirmed orders. The issue is that I need to create a certain number of variants manually, but this is not possible. The creation does not allow me edit the variant attribute.

Any help possible on that?

Thanks
Eva P.

**Comment by pedrobaeza** [comment]
You have two ways:
- Go to product variants, and create it there.
- Go to products (templates), click create, and on variants tab, unmark check "Don't create variants automatically", and continue creating the attributes the regular way.

**Comment by ybofr** [comment]
The first way does not work...I would not have asked you such a trivial question ;-). I am not able to choose the attributes values, when I go to create variants.

I do not have a checkbox Don't create variant automatically. I have a list. But, if I now select to create the variant automatically, I will have 4000 variants created immediately, what I do not want.

So, I do not see how to create this manually.

---

Eva P.

Affordable high quality training on Odoo-training.com http://odoo-training.com/

**Comment by pedrobaeza** [comment]
Ah, OK, you want to create a specific variant for a general template. That can't be achieved, because it's not a use case, but you can do a trick with another module:
- Create a single product variant, that creates its template.
- Install _product_template_reassign_ module.
- Go to the template with attributes.
- Select More > Product template reassign (or something similar).
- For the specific variant needed, search and put that created single product.

**Comment by ybofr** [comment]
Thanks Pedro. I will try it.

## Regards

Eva P.

Affordable high quality training on Odoo-training.com http://odoo-training.com/
