### ISSUE TITLE
mrp_operations_extensions losing separation of concern?

### ISSUE THREAD

**Issue by clonedagain** [odoomrp/odoomrp-wip#835]
As noticed in #753, `operation_extension` now depends on `hr`.
It's not obvious to me what `hr` is used for here ; it looks like a costing feature but the README of the module doesn't announce anything of the sort.
Maybe the module has overgrown and we could split some features out of it ? Modules named `*_extension` often tend to get bloated as time goes, so we should strive to keep it under control.
I for one am very uneasy about forcing HR onto my users, who are not prepared at all.

**Comment by clonedagain** [comment]
I'll probably be able to help with cleanly separating concerns here, but guidance would be of great value.
Can someone please review/update the README first ?

**Comment by clonedagain** [comment]
@pedrobaeza @anajuaristi would you accept to split operation_extension in smaller bits?

**Comment by anajuaristi** [comment]
IMHO split is not necesary

If you want people including hours / time and costs on operations you would need HR 
Dependency is just with HR employée master table so i don't think so is a very big issue having it installed. 

@pedrobaeza I vote not to split since we have got enormous quantity of small modules by now. But, I let you take decision.

Thank you @clonedagain

**Comment by anajuaristi** [comment]
No comment, so I'm closing
