### ISSUE TITLE
Quality Control - Stock Picking View for Saleman

### ISSUE THREAD

**Issue by sluggogle** [odoomrp/odoomrp-wip#993]
Hi,
Thx again for your modules, it really helps build a coherent system for a company.

I have an issue with access rights regarding the module: quality_control_stock
My saleman can no longer access to delivery orders because the system requires him to have qc.inspection/User rights.

QC buttons should be hidden when the user isn't part of the security group
Hope you could fix this.
Thank you

**Comment by pedrobaeza** [comment]
The problem is that stock module doesn't know about sale module. The module _sale_stock_ is the one that communicates both, so I have made another glue module, _quality_control_sale_stock_, that fix the permission when _sale_stock_ is installed.

About the buttons visibility, it depends, because salesmen may want to see if there's any pending or failure quality inspections to tell their customers.
