### ISSUE TITLE
mrp_production_real_costs: Issue with average cost for incomming products ?

### ISSUE THREAD

**Issue by cor9003** [odoomrp/odoomrp-wip#998]
Hello, 
I'm checking this module and before to install, the standard odoo functionality, upgraded the product average cost by every incoming goods of those products were been bought through purchases orders. After install this module this estandard functionality is not working any more
I think If this module is to update cost for MO , should not stop this standard functionality for those products are only buyed and not need manufacturing ?, like row materials ....
Is this an issue ?

**Comment by pedrobaeza** [comment]
This module doesn't change anything in average cost except a button for dumping the real cost to product. Please check again if your problem comes from this module.

**Comment by cor9003** [comment]
Hello Pedro,
I confirm you that with the mrp_production_real_costs installed, the products  are not updated the  cost price in the procurement tab when a incomming goods has been done. The checking done again has been:
1) Create a ne DB with the standard modules of purchaes, sales, accounting, warehouse and MRP
2) Create a single provider, and a material with costing method "average price" and cost price setup to 0€
3) Create a purchase order for this material assigning a price of 1€, confirm and create the incoming goods of this purchase order
After it, the price cost of this product has been updated to 1€ that is Ok because it is the price created in the purchase order

The sames steps done but with the difference of to add the module mrp_production_real_costs in steep 1, the result is the price cost in the procurement tab has not been updated, it is still to 0€

**Comment by cor9003** [comment]
Sorry Pedro,

After more detailed checking, I see that a variant has been created with a field named Variant Cost Price, that this values has been updated fine. But the the root cost price no.
When we create a purchase order the value that get the estimated prices still being 0€ because do not use the variant price cost.
Is correct the functionality ?

**Comment by cor9003** [comment]
Thanks for your support Pedro

**Comment by pedrobaeza** [comment]
Prices are handled on variants, not on templates, so it's correct the behaviour. I close this.

**Comment by vafonso** [comment]
Hello guys, 
I started to use this module here and I figure out that if the root cost price is not updated, all Jornal Entries under Accounts have incorrect values.
Account module use the root cost price as basis

Vinicius from Brazil

**Comment by anajuaristi** [comment]
If each variant has got its own cost it has nosense updating template cost
so to solve your issues on accounting moves you should make a patch to make
cost price to be taken from product.
Other solution would be not using variants or going through version 9 where
cost is on variant on odoo core so I think account move will be rigth on
that version.

**Comment by vafonso** [comment]
Hi Ana, thanks a lot for the real fast answer.
Could you please be so kind to detail a bit more how to do this patch?
Which code part do you suggest to change ?

Unfortunately version 9 is far from Brazil due our accounts localization.

Thanks for your support.
Kind regards

**Comment by vafonso** [comment]
What I have done so far was to change the odoo/addons/stock_account/stock_account.py file.
I've changed:
Under def _prepare_account_move_line
1. valuation_amount = cost if move.location_id.usage != 'internal' and move.location_dest_id.usage == 'internal' else move.product_id.standard_price TO valuation_amount = cost if move.location_id.usage != 'internal' and move.location_dest_id.usage == 'internal' else move.product_id.cost_price
2. valuation_amount = cost if move.product_id.cost_method == 'real' else move.product_id.standard_price TO valuation_amount = cost if move.product_id.cost_method == 'real' else move.product_id.cost_price

Under def product_price_update_before_done
amount_unit = product.standard_price TO amount_unit = product.cost_price

After that, I figure out that the Jornal Entries are OK for the BOM materials, but the last post (When we finished the order in which should sum the BOM cost plus operation costs) is missing the operation costs. That means only the BOM costs is posted.
It seams that the costs are correctly computed on the Item, but the Odoo core first make the Jornal Entries and after your module is compute the overall costs.
Since Odoo core is first, it take only the costs that are in the item before your module acts.
Could you please help how to invert this process? I mean, first your module need to run and after Odoo core go to write the Jornal Entries.

Thanks again

Vinicius from Brazil

**Comment by anajuaristi** [comment]
Hi @vafonso 

If you change directly odoo/addons/stock_account/stock_account.py file, you are forking the core so it will not be easy to mantain. 

If you want to start developping Odoo I recomend to you to try a full technical training to learn how to use inheritance and other good practices tools.

**Comment by pedrobaeza** [comment]
I have told in other occasions: with the module https://github.com/OCA/product-variant/pull/14 + adapting mrp_production_real_costs to this module, everything will be handled transparently. Next steps to do:
- Add tests to the PR to accept the module with enough guarantees.
- Adapt _mrp_production_project_estimated_cost_ to this new module.
- Adapt _mrp_production_real_costs_ to this new module.
- Remove the other field and forget it forever as it was a bad dream. :stuck_out_tongue_winking_eye:

**Comment by vafonso** [comment]
Hi Ana, thanks for your feedback. You're right. I need first update my knowledge about odoo best pratices before start to change anything. The idea was just to find what module was taking care of this cost and check if the end result was ok.
I will try my best to make this more professional and in a correct way. And If I got it, I post it to you.

Kind regards

Vinicius

**Comment by vafonso** [comment]
Hi Ana,
As I informed, I tried to study the variant cost code to try to have the average cost in root cost price (template price)
Please could you help me and analyze if I inheritance the def _store_average_cost_price and def product_price_update_before_done in stock_quant from product variant cost (or maybe ask for a pull request), inserting the following line: product.sudo().write({'standard_price': average_valuation_price}) by the end of each function, Odoo will populated the calculated cost also in the standard (root) cost price field.
With that, the stock transactions under accounts are correct.

This could be an interim solution till the product-variant#14 is not finish
Thanks
